### ISSUE TITLE
Export `LangClassifier` to onnx

### ISSUE THREAD

**Issue by evdcush** [kaiyuyue/nxtp#2]
Thanks for providing code and checkpoints for your method! 🙇🏻‍♂️ 

The method is interesting, but the paper lacks any basic diagram or graphic explaining the model architecture at a high level.

In order to get a coarse understanding of the model architecture, I thought it would be helpful to export the model to onnx format, and use Netron to visualize the arch.

It was a decently involved process to get `nxtp/src/infer.py` runnable, but after a good amount of effort I got it running, and attempted to `torch.onnx.export` the model.

So, I ran:

```python
torch.onnx.export(model, img, 'nxtp_g3m_model.onnx')
```

But it looks like `LangClassifier` has a dummy `forward`, which I've not seen before in `nn.Module` implementations. Maybe a regular python class would have been more suitable, but at any rate, I was still hoping to export the outer-most meta architecture for your method.

May I request you provide an `onnx` file for `nxtp`, or maybe document how to export the model to onnx?

**Comment by kaiyuyue** [comment]
Hi, please see [docs/README.md#onnx-export](https://github.com/kaiyuyue/nxtp/blob/main/docs/README.md#onnx-export).
