### ISSUE TITLE
can put the llama model param json file and tokenizer file into google driver ?

### ISSUE THREAD

**Issue by zimenglan-sysu-512** [kaiyuyue/nxtp#4]
hi @kaiyuyue 
since i can't download the llama2-7b file forbidden by the connection, can put the llama model param json file and tokenizer file into google driver?

**Comment by kaiyuyue** [comment]
Can you try download them from huggingface? Here is the [link](https://huggingface.co/meta-llama/Llama-2-7b/tree/main). You can click one of them and will get the download link there. Then use `wget` to download on your machine. Hope it is helpful.

**Comment by zimenglan-sysu-512** [comment]
fatal: Authentication failed for 'https://huggingface.co/meta-llama/Llama-2-7b/'

**Comment by kaiyuyue** [comment]
need to login and accept the policy. then should be good for downloading.
<img width="808" alt="image" src="https://github.com/user-attachments/assets/795c0793-7a78-4f18-9e9e-2c7f6d9cda07">

**Comment by kaiyuyue** [comment]
all good?

**Comment by zimenglan-sysu-512** [comment]
not yet, still encounter the problem "Proxy request sent, awaiting response... 403 Forbidden".

**Comment by kaiyuyue** [comment]
[g-drive](https://drive.google.com/drive/folders/1Kr9Q-DdLrk3rmYf_UCloE0VMziB9r6rn?usp=share_link)

**Comment by zimenglan-sysu-512** [comment]
hi. @kaiyuyue 
thanks a lot, now i can download the llama pretrained model, and run the infer.py to get the result as below using `config_g70m` and `ckpt_epoch_03_iter_1656549.pth` for `assets/starbux.jpg` image :
```
=> [infer], [main], top-20 predictions:
| prob: 0.14856 - coffee
| prob: 0.10406 - shop
| prob: 0.08066 - counter
| prob: 0.04603 - bar
| prob: 0.04054 - restaurant
| prob: 0.03690 - inside
| prob: 0.03467 - area
| prob: 0.02637 - store
| prob: 0.02236 - table
| prob: 0.01929 - interior
| prob: 0.01347 - lot
| prob: 0.01156 - food
| prob: 0.01057 - customer
| prob: 0.01001 - room
| prob: 0.00923 - starbucks
| prob: 0.00853 - bakery
| prob: 0.00738 - view
| prob: 0.00738 - floor
| prob: 0.00732 - cafe
| prob: 0.00633 - shelf
```

does it look normally?

**Comment by kaiyuyue** [comment]
Yes

**Comment by zimenglan-sysu-512** [comment]
get it, thanks a lot.

**Comment by kaiyuyue** [comment]
please remember pulling the new code since I update the data loader.

**Comment by zimenglan-sysu-512** [comment]
ok, get it.
