### ISSUE TITLE
Will test datasets be released?

### ISSUE THREAD

**Issue by huangyjhust** [kaiyuyue/nxtp#6]
It seems test labels parsed from CC3M, COCO and OpenImages remain in-house. 
Third-party reimplementing A.5 Preprocessing would cause diffs in following method and hinders matching results to yours. 
Are you planning to update your in-house evaluation annotations?

**Comment by kaiyuyue** [comment]
- The ground-truth labels are extracted from the original captions by [src/evals/engine.py#L119](https://github.com/kaiyuyue/nxtp/blob/main/src/evals/engine.py#L119) and the eval script is [docs/README.md#evaluation](https://github.com/kaiyuyue/nxtp/blob/main/docs/README.md#evaluation). 

- The preprocessing for both training and evaluation is [src/utils.py#L256](https://github.com/kaiyuyue/nxtp/blob/main/src/utils.py#L256).

Hope these could help.
