### ISSUE TITLE
Download CC3M and OpenImages

### ISSUE THREAD

**Issue by sorrowyn** [kaiyuyue/nxtp#7]
Great work! I encountered a few issues while downloading the datasets:

For CC3M, I did not use the "img2dataset" tool but instead downloaded it directly from Hugging Face, which includes 2.9M training samples and 13.4K validation samples.

For OpenImageV7, could you please share how you downloaded it? This will help me process this part of the dataset later. It would be ideal if you could also provide the necessary code.

**Comment by kaiyuyue** [comment]
It can be downloaded from [openimages/web/download_v7.html#image-labels-subset](https://storage.googleapis.com/openimages/web/download_v7.html#image-labels-subset). Then for packing the pairs of image and caption into tars, refer to [docs/README.md#packing-image-caption-pairs](https://github.com/kaiyuyue/nxtp/blob/main/docs/README.md#packing-image-caption-pairs).

Here is the script I used for processing openimages. Hope this could help.

```python
#!/usr/bin/env python
# coding: utf-8
#
# Usage:
#   python3 openimages_to_wds.py

import os
import os.path as osp
import json
import shutil
from tqdm import tqdm

root = "/data/openimages_v7"
save_dir = osp.join(root, "openimages_v7_valid")

if not os.path.exists(save_dir):
    os.makedirs(save_dir)

json_file_path = osp.join(root, "open_images_validation_localized_narratives.jsonl")
sub_fold_cnt = 1
with open(json_file_path, "r") as f:
    for i, line in tqdm(enumerate(f)):
        line = json.loads(line)
        image_id = line["image_id"]

        cap = line["caption"]
        src = osp.join(root, "valid", f"{image_id}.jpg")

        if (i + 1) % 2999 == 0:
            sub_fold_cnt += 1
        sub_fold = osp.join(save_dir, str(sub_fold_cnt - 1).zfill(5))
        if not os.path.exists(sub_fold):
            os.makedirs(sub_fold)

        img_path = osp.join(root, sub_fold, f"{image_id}.jpg")
        txt_path = osp.join(root, sub_fold, f"{image_id}.txt")
        jsn_path = osp.join(root, sub_fold, f"{image_id}.json")

        shutil.copy(src, img_path)

        with open(txt_path, "w") as f:
            f.write(cap)

        with open(jsn_path, "w") as f:
            json.dump(line, f)
```

**Comment by sorrowyn** [comment]
> It can be downloaded from [openimages/web/download_v7.html#image-labels-subset](https://storage.googleapis.com/openimages/web/download_v7.html#image-labels-subset). Then for packing the pairs of image and caption into tars, please refer to [docs/README.md#packing-image-caption-pairs](https://github.com/kaiyuyue/nxtp/blob/main/docs/README.md#packing-image-caption-pairs).
> 
> Here is the script I used for processing openimages. Hope this could help.
> 
> ```python
> #!/usr/bin/env python
> # coding: utf-8
> #
> # Usage:
> #   python3 openimages_to_wds.py
> 
> import os
> import os.path as osp
> import json
> import shutil
> from tqdm import tqdm
> 
> root = "/data/openimages_v7"
> save_dir = osp.join(root, "openimages_v7_valid")
> 
> if not os.path.exists(save_dir):
>     os.makedirs(save_dir)
> 
> json_file_path = osp.join(root, "open_images_validation_localized_narratives.jsonl")
> sub_fold_cnt = 1
> with open(json_file_path, "r") as f:
>     for i, line in tqdm(enumerate(f)):
>         line = json.loads(line)
>         image_id = line["image_id"]
> 
>         cap = line["caption"]
>         src = osp.join(root, "valid", f"{image_id}.jpg")
> 
>         if (i + 1) % 2999 == 0:
>             sub_fold_cnt += 1
>         sub_fold = osp.join(save_dir, str(sub_fold_cnt - 1).zfill(5))
>         if not os.path.exists(sub_fold):
>             os.makedirs(sub_fold)
> 
>         img_path = osp.join(root, sub_fold, f"{image_id}.jpg")
>         txt_path = osp.join(root, sub_fold, f"{image_id}.txt")
>         jsn_path = osp.join(root, sub_fold, f"{image_id}.json")
> 
>         shutil.copy(src, img_path)
> 
>         with open(txt_path, "w") as f:
>             f.write(cap)
> 
>         with open(jsn_path, "w") as f:
>             json.dump(line, f)
> ```

Thank you for your help, this is very good news. Here is how to download the images and other necessary files.
```shell
# download validation set
pip install awscli
mkdir openimages_v7
aws s3 --no-sign-request cp s3://open-images-dataset/tar/validation.tar.gz openimages_v7

# download open_images_validation_localized_narratives file
wget https://storage.googleapis.com/localized-narratives/annotations/open_images_validation_localized_narratives.jsonl
```

**Comment by sorrowyn** [comment]
Hi @kaiyuyue！Since I am located in the China time zone, I need to use a VPN to download the sbu_captions dataset. However, I have encountered several issues:

1: The instability of the VPN has made it difficult to download many images, even after trying multiple VPN services.

2: I also attempted to download the dataset using the "eaglewatch/sbucaptions" project on Hugging Face, but this approach was unsuccessful.

I kindly request your assistance in analyzing this dataset through Google Drive.

**Comment by kaiyuyue** [comment]
Can you try to download from [kaggle/sbuCaptions](https://www.kaggle.com/datasets/akashnuka/sbucaptions/data)? The download button is on the top-right corner.

**Comment by sorrowyn** [comment]
> Can you try to download it from [kaggle/sbuCaptions](https://www.kaggle.com/datasets/akashnuka/sbucaptions/data) without VPN? The download button is on the top-right corner.
> 
> <img alt="image" width="1919" src="https://private-user-images.githubusercontent.com/19852297/397153164-76886fea-d8ab-4826-8361-60d2531fc5bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1NjM2NzEsIm5iZiI6MTczNDU2MzM3MSwicGF0aCI6Ii8xOTg1MjI5Ny8zOTcxNTMxNjQtNzY4ODZmZWEtZDhhYi00ODI2LTgzNjEtNjBkMjUzMWZjNWJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDIzMDkzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiOGM3OTliNDZmNGQ2ZmYyZTk2NDA1OTllZWNhN2JhZjkyZGE5ODIwYjIzYjA4YThkOWFkODJmY2NiNGM3ZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.E5dNHGQu92zzx4XCIAsftmkiRiGo6YPUaLPn3pYS8HE">

Thanks for your advice and guidance. It took me about 30 minutes to complete this using the method you recommended.
Best for you!
